const tagData={
	"region":{
		title:"地区",
		list:[
			{'name_ch':'卡拉布里亚','name_en':''},
			{'name_ch':'瓦莱塔奥斯塔','name_en':''},
			{'name_ch':'托斯卡纳','name_en':''},
			{'name_ch':'阿布鲁佐','name_en':''},
			{'name_ch':'特伦蒂诺-上阿迪杰','name_en':''},
			{'name_ch':'皮埃蒙特','name_en':''},
			{'name_ch':'维纳图','name_en':''},
			{'name_ch':'艾米利亚-罗马涅','name_en':''},
			{'name_ch':'马尔奇','name_en':''},
			{'name_ch':'坎帕尼亚','name_en':''},
			{'name_ch':'翁布里亚','name_en':''},
			{'name_ch':'撒丁岛','name_en':''},
			{'name_ch':'巴斯利卡塔','name_en':''},
			{'name_ch':'拉齐奥','name_en':''},
			{'name_ch':'伦巴第','name_en':''},
			{'name_ch':'西西里岛','name_en':''},
			{'name_ch':'普利亚','name_en':''},
			{'name_ch':'利古里亚','name_en':''},
			{'name_ch':'莫利塞','name_en':''},
			{'name_ch':'弗留利-威尼斯朱利亚','name_en':''},
			{'name_ch':'圣马力诺产区','name_en':''}
		]
	},
	"wine_type":{
		title:"葡萄酒类型",
		list:[
			{'name_ch':'红葡萄酒','name_en':''},
			{'name_ch':'起泡酒','name_en':''},
			{'name_ch':'白葡萄酒','name_en':''},
			{'name_ch':'桃红葡萄酒','name_en':''},
			{'name_ch':'格拉帕酒','name_en':''},
			{'name_ch':'加强型葡萄酒','name_en':''},
			{'name_ch':'甜葡萄酒','name_en':''},
			{'name_ch':'干邑','name_en':''},
			{'name_ch':'白兰地','name_en':''}
		]
	},
	"grape":{
		title:"葡萄品种",
		list:[
			{'name_ch':'赤霞珠','name_en':''},
			{'name_ch':'霞多丽','name_en':''},
			{'name_ch':'西拉','name_en':''},
			{'name_ch':'美乐','name_en':''},
			{'name_ch':'歌海娜','name_en':''},
			{'name_ch':'黑比诺','name_en':''},
			{'name_ch':'品丽珠','name_en':''},
			{'name_ch':'马尔贝克','name_en':''},
			{'name_ch':'白莫斯卡托','name_en':''},
			{'name_ch':'白诗南','name_en':''},
			{'name_ch':'添普兰尼洛','name_en':''},
			{'name_ch':'慕合怀特','name_en':''},
			{'name_ch':'赛美蓉','name_en':''},
			{'name_ch':'玛尔维萨','name_en':''},
			{'name_ch':'灰比诺','name_en':''},
			{'name_ch':'维欧尼','name_en':''},
			{'name_ch':'长相思','name_en':''},
			{'name_ch':'小味儿多','name_en':''},
			{'name_ch':'麝香','name_en':''},
			{'name_ch':'内比奥罗','name_en':''},
			{'name_ch':'佳美娜','name_en':''},
			{'name_ch':'神索','name_en':''},
			{'name_ch':'黑达沃拉','name_en':''},
			{'name_ch':'佳美','name_en':''},
			{'name_ch':'密斯卡岱','name_en':''},
			{'name_ch':'黑曼罗','name_en':''},
			{'name_ch':'琼瑶浆','name_en':''},
			{'name_ch':'奥图歌','name_en':''},
			{'name_ch':'小芒森','name_en':''},
			{'name_ch':'桑娇维塞','name_en':''},
			{'name_ch':'马家婆','name_en':''},
			{'name_ch':'华帝露','name_en':''},
			{'name_ch':'小西拉','name_en':''},
			{'name_ch':'佳利酿','name_en':''},
			{'name_ch':'白玉霓','name_en':''}
		]
	}
}
export default tagData
